### ISSUE TITLE
Why is this not in NPM?

### ISSUE THREAD

**Issue by rclai** [anonyco/SPromiseMeSpeedJS#1]
Looks great.

**Comment by anonyco** [comment]
Thank you for bringing this to my attention and for your praise gratifying the work I put into this project. I'll post it up to npm and integrate es6 module support as soon as I get some spare time today.

~ Happy coding!

**Comment by anonyco** [comment]
I apologize for taking so much longer, but it may be longer. I probably won't be ready to push the npm integration until tomorrow....I am revamping the way that I integrate my libraries into npm to make mt npm repositories cleaner, leaner, and faster. I hope that this delay does not disrupt your work.

**Comment by rclai** [comment]
No don't worry man, no rush.

**Comment by anonyco** [comment]
Thank you. I have published this library to npm in commit [538bedd](https://github.com/anonyco/SPromiseMeSpeedJS/commit/538beddb4c7f826f80cd9222ac396acf792da3a0).
